variables:
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: naamio/kauppa #$CI_REGISTRY_IMAGE
  CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME #$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CONTAINER_IMAGE:latest #$CI_REGISTRY_IMAGE:latest

stages:
  - test
  - build
  - deploy

build:linux:
  image: ibmcom/swift-ubuntu:4.0
  stage: build
  before_script:
    # install ssh-agent
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    # run ssh-agent
    - eval $(ssh-agent -s)

    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")

    # disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks)
    # WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Building release artifact"
    - swift build -c release -Xcc -fblocks -Xlinker -L/usr/local/lib
  artifacts:
    paths:
    - .build/release/*
    expire_in: 1 week
  tags:
    - docker
  only:
    - schedules
    - master
    - release

review:
  image: ibmcom/swift-ubuntu:4.0
  stage: test
  script:
    - echo "Reviewing $CI_PROJECT_NAME"
    - make build
    - make test
  only:
    - branches
  except:
    - master

test:
  image: ibmcom/swift-ubuntu:4.0
  stage: test
  script:
    - echo "Testing $CI_PROJECT_NAME"
    - make test
  tags:
    - docker
  only:
    - master
  artifacts:
    paths:
    - .build/debug/*

build:container:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - echo -n $DOCKER_HUB_SECRET | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f Dockerfile .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
    - ls Sources | while read service; do \
        if [ -f "Sources/$service/main.swift" ]; then \
            SERVICE_NAME=$(echo $service | sed 's/\([A-Z]\)/ \1/g' | cut -d' ' -f3 | tr '[:upper:]' '[:lower:]') ; \
            echo 'Building' $CONTAINER_IMAGE-$SERVICE_NAME ; \
            docker build -t $CONTAINER_IMAGE:$SERVICE_NAME-$CI_BUILD_REF_NAME -f Sources/$service/Dockerfile . ; \
        fi ; \
      done
    - docker images | grep $CONTAINER_IMAGE.*$CI_BUILD_REF_NAME | awk -v OFS=':' '{print $1,$2}' | xargs docker push
  when: manual
  tags:
    - docker
  only:
    - release
  dependencies:
    - build:linux

tag:container:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - echo -n $DOCKER_HUB_SECRET | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f Dockerfile .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
    - ls Sources | while read service; do \
        if [ -f "Sources/$service/main.swift" ]; then \
            SERVICE_NAME=$(echo $service | sed 's/\([A-Z]\)/ \1/g' | cut -d' ' -f3 | tr '[:upper:]' '[:lower:]') ; \
            echo 'Building' $CONTAINER_IMAGE-$SERVICE_NAME ; \
            docker build -t $CONTAINER_IMAGE:$SERVICE_NAME-$CI_BUILD_REF_NAME -f Sources/$service/Dockerfile . ; \
        fi ; \
      done
    - docker images | grep $CONTAINER_IMAGE.*$CI_BUILD_REF_NAME | awk -v OFS=':' '{print $1,$2}' | xargs docker push
  when: manual
  tags:
    - docker
  only:
    - tags
  dependencies:
    - build:linux

nightly:container:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - echo -n $DOCKER_HUB_SECRET | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f Dockerfile .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_IMAGE:nightly
    - docker push $CONTAINER_IMAGE:nightly
    - ls Sources | while read service; do \
        if [ -f "Sources/$service/main.swift" ]; then \
            SERVICE_NAME=$(echo $service | sed 's/\([A-Z]\)/ \1/g' | cut -d' ' -f3 | tr '[:upper:]' '[:lower:]') ; \
            echo 'Building' $CONTAINER_IMAGE-$SERVICE_NAME ; \
            docker build -t $CONTAINER_IMAGE:$SERVICE_NAME-nightly -f Sources/$service/Dockerfile . ; \
        fi ; \
      done
    - docker images | grep $CONTAINER_IMAGE.*nightly | awk -v OFS=':' '{print $1,$2}' | xargs docker push
  when: on_success
  tags:
    - docker
  only:
    - schedules
  dependencies:
    - build:linux
